export const youHomeimages = [
    { src: "/homestudio/implantacao/bolotario6/galeria/img-apto1.png", alt: 'Imagem 1' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-apto2.png", alt: 'Imagem 2' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-brinquedoteca.png", alt: 'Imagem 3' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-coworking.png", alt: 'Imagem 4' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-delivery.png", alt: 'Imagem 5' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-entregas.png", alt: 'Imagem 6' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fachada-3.png", alt: 'Imagem 7' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fachada1.png", alt: 'Imagem 8' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fachada2.png", alt: 'Imagem 9' }, 
    { src: "/homestudio/implantacao/bolotario6/galeria/img-festas.png", alt: 'Imagem 10' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fitness.png", alt: 'Imagem 11' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-gourmet.png", alt: 'Imagem 12' },       
    { src: "/homestudio/implantacao/bolotario6/galeria/img-grill-space.png", alt: 'Imagem 13' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-hall.png", alt: 'Imagem 14' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-hub-jogos.png", alt: 'Imagem 15' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-jogos-teen.png", alt: 'Imagem 16' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-lavanderia.png", alt: 'Imagem 17' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-lounge-zen.png", alt: 'Imagem 18' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-massagem.png", alt: 'Imagem 19' },   
    { src: "/homestudio/implantacao/bolotario6/galeria/img-mini-mercado.png", alt: 'Imagem 20' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-pet-care.png", alt: 'Imagem 21' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-pet-place.png", alt: 'Imagem 22' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina-rooftop.png", alt: 'Imagem 23' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina2.png", alt: 'Imagem 24' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina3.png", alt: 'Imagem 25' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina4.png", alt: 'Imagem 26' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-playground.png", alt: 'Imagem 27' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-porte.png", alt: 'Imagem 28' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-quadra.png", alt: 'Imagem 29' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-reuniao.png", alt: 'Imagem 30' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-rooftop.png", alt: 'Imagem 31' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-sauna.png", alt: 'Imagem 32' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-wine.png", alt: 'Imagem 33' },
]


export const expandedYouHomeImages = [
    { src: "/homestudio/implantacao/expanded/3708-1.png", alt: 'Imagem Expandida 1' },
    { src: "/homestudio/implantacao/expanded/3708.png", alt: 'Imagem Expandida 2' },
    { src: "/homestudio/implantacao/expanded/brinquedoteca.png", alt: 'Imagem Expandida Brinquedoteca' },
    { src: "/homestudio/implantacao/expanded/coworking.png", alt: 'Imagem Expandida Coworking' },
    { src: "/homestudio/implantacao/expanded/fachada.png", alt: 'Imagem Expandida Fachada' },
    { src: "/homestudio/implantacao/expanded/fachada2.png", alt: 'Imagem Expandida Fachada 2' },
    { src: "/homestudio/implantacao/expanded/fachada3.png", alt: 'Imagem Expandida Fachada 3' },   
    { src: "/homestudio/implantacao/expanded/festas.png", alt: 'Imagem Expandida Festas' },
    { src: "/homestudio/implantacao/expanded/fitness.png", alt: 'Imagem Expandida Fitness' },
    { src: "/homestudio/implantacao/expanded/gourmet.png", alt: 'Imagem Expandida Gourmet' },
    { src: "/homestudio/implantacao/expanded/grill.png", alt: 'Imagem Expandida Grill' },
    { src: "/homestudio/implantacao/expanded/hub.png", alt: 'Imagem Expandida Hub' },
    { src: "/homestudio/implantacao/expanded/jogos-teen.png", alt: 'Imagem Expandida Jogos Teen' },
    { src: "/homestudio/implantacao/expanded/lobby.png", alt: 'Imagem Expandida Lobby' },
    { src: "/homestudio/implantacao/expanded/lounge-zen.png", alt: 'Imagem Expandida Lounge Zen' },
    { src: "/homestudio/implantacao/expanded/massagem.png", alt: 'Imagem Expandida Massagem' },
    { src: "/homestudio/implantacao/expanded/petplace.png", alt: 'Imagem Expandida Pet Place' },
    { src: "/homestudio/implantacao/expanded/piscina-rooftop.png", alt: 'Imagem Expandida Piscina Rooftop' },
    { src: "/homestudio/implantacao/expanded/piscina-rooftop2.png", alt: 'Imagem Expandida Piscina Rooftop 2' },
    { src: "/homestudio/implantacao/expanded/piscina-rooftop3.png", alt: 'Imagem Expandida Piscina Rooftop 3' },
    { src: "/homestudio/implantacao/expanded/piscina.png", alt: 'Imagem Expandida Piscina' },
    { src: "/homestudio/implantacao/expanded/playground.png", alt: 'Imagem Expandida Playground' },
    { src: "/homestudio/implantacao/expanded/pool.png", alt: 'Imagem Expandida Pool' },
    { src: "/homestudio/implantacao/expanded/porte.png", alt: 'Imagem Expandida Porte' },
    { src: "/homestudio/implantacao/expanded/quadra.png", alt: 'Imagem Expandida Quadra' },
    { src: "/homestudio/implantacao/expanded/reunião.png", alt: 'Imagem Expandida Reunião' },
    { src: "/homestudio/implantacao/expanded/sauna.png", alt: 'Imagem Expandida Sauna' },
    { src: "/homestudio/implantacao/expanded/wine.png", alt: 'Imagem Expandida Wine' },
];
