export const youHomeimages = [
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fachada1.png", alt: 'Imagem 8' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fachada2.png", alt: 'Imagem 9' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fachada-3.png", alt: 'Imagem 7' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-porte.png", alt: 'Imagem 28' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-hall.png", alt: 'Imagem 14' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-rooftop.png", alt: 'Imagem 31' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina-rooftop.png", alt: 'Imagem 23' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina2.png", alt: 'Imagem 24' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina3.png", alt: 'Imagem 25' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-piscina4.png", alt: 'Imagem 26' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-fitness.png", alt: 'Imagem 11' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-massagem.png", alt: 'Imagem 19' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-lounge-zen.png", alt: 'Imagem 18' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-sauna.png", alt: 'Imagem 32' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-grill-space.png", alt: 'Imagem 13' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-gourmet.png", alt: 'Imagem 12' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-playground.png", alt: 'Imagem 27' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-pet-place.png", alt: 'Imagem 22' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-quadra.png", alt: 'Imagem 29' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-festas.png", alt: 'Imagem 10' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-hub-jogos.png", alt: 'Imagem 15' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-jogos-teen.png", alt: 'Imagem 16' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-wine.png", alt: 'Imagem 33' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-coworking.png", alt: 'Imagem 4' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-reuniao.png", alt: 'Imagem 30' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-brinquedoteca.png", alt: 'Imagem 3' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-apto1.png", alt: 'Imagem 1' },
    { src: "/homestudio/implantacao/bolotario6/galeria/img-apto2.png", alt: 'Imagem 2' },
]


export const expandedYouHomeImages = [
    { src: "/homestudio/implantacao/expanded/fachada.png", alt: ' Fachada' },
    { src: "/homestudio/implantacao/expanded/2.png", alt: ' Fachada' },
    { src: "/homestudio/implantacao/expanded/3.png", alt: ' Fachada' },
    { src: "/homestudio/implantacao/expanded/4.png", alt: ' porte-cochère' },
    { src: "/homestudio/implantacao/expanded/5.png", alt: ' Lobby Social' },
    { src: "/homestudio/implantacao/expanded/6.png", alt: ' Piscina Rooftop' },
    { src: "/homestudio/implantacao/expanded/7.png", alt: ' Piscina Rooftop' },
    { src: "/homestudio/implantacao/expanded/8.png", alt: ' Piscina Rooftop' },
    { src: "/homestudio/implantacao/expanded/9.png", alt: ' Piscina' },
    { src: "/homestudio/implantacao/expanded/10.png", alt: ' Pool House' },
    { src: "/homestudio/implantacao/expanded/11.png", alt: ' Fitness' },
    { src: "/homestudio/implantacao/expanded/12.png", alt: ' Massagem' },
    { src: "/homestudio/implantacao/expanded/13.png", alt: ' Lounge Zen' },
    { src: "/homestudio/implantacao/expanded/14.png", alt: ' Sauna' },
    { src: "/homestudio/implantacao/expanded/15.png", alt: ' Grill Space' },
    { src: "/homestudio/implantacao/expanded/16.png", alt: 'Espaço Gourmet' },
    { src: "/homestudio/implantacao/expanded/17.png", alt: ' Playground' },
    { src: "/homestudio/implantacao/expanded/18.png", alt: ' Pet Place' },
    { src: "/homestudio/implantacao/expanded/19.png", alt: ' Quadra Recreativa' },
    { src: "/homestudio/implantacao/expanded/20.png", alt: 'Salão de Festas' },
    { src: "/homestudio/implantacao/expanded/21.png", alt: ' Hub de Jogos' },
    { src: "/homestudio/implantacao/expanded/22.png", alt: 'Salão de Jogos Teen' },
    { src: "/homestudio/implantacao/expanded/23.png", alt: ' Wine Lounge' },
    { src: "/homestudio/implantacao/expanded/24.png", alt: ' Coworking' },
    { src: "/homestudio/implantacao/expanded/25.png", alt: ' Sala de Reunião' },
    { src: "/homestudio/implantacao/expanded/26.png", alt: ' Brinquedoteca' },
    { src: "/homestudio/implantacao/expanded/27.png", alt: ' YouHome 3708' },
    { src: "/homestudio/implantacao/expanded/28.png", alt: ' YouHome 3708' },
];
