export const youHomeimages = [
    { src: "/homestudio/youstudio/imagens/img-fachada1.png", alt: 'Imagem 1' },
    { src: "/homestudio/youstudio/imagens/img-fachada2.png", alt: 'Imagem 2' },
    { src: "/homestudio/youstudio/imagens/img-fachada-3.png", alt: 'Imagem 3' },
    { src: "/homestudio/youstudio/imagens/img-porte.png", alt: 'Imagem 4' },
    { src: "/homestudio/youstudio/imagens/img-hall.png", alt: 'Imagem 5' },
    { src: "/homestudio/youstudio/imagens/img-repouso.png", alt: 'Imagem 6' },
    { src: "/homestudio/youstudio/imagens/img-sauna.png", alt: 'Imagem 7' },
    { src: "/homestudio/youstudio/imagens/img-fitstudio.png", alt: 'Imagem 8' },
    { src: "/homestudio/youstudio/imagens/img-gourmet.png", alt: 'Imagem 9' },
    { src: "/homestudio/youstudio/imagens/img-lavanderia.png", alt: 'Imagem 10' },
    { src: "/homestudio/youstudio/imagens/img-coworking.png", alt: 'Imagem 11' },
    { src: "/homestudio/youstudio/imagens/img-studio.png", alt: 'Imagem 12' },
    { src: "/homestudio/youstudio/imagens/img-studio2.png", alt: 'Imagem 13' },
    { src: "/homestudio/youstudio/imagens/img-delivery.png", alt: 'Imagem 14' },
    { src: "/homestudio/youstudio/imagens/img-entregas.png", alt: 'Imagem 15' },
    { src: "/homestudio/youstudio/imagens/img-pet-care.png", alt: 'Imagem 16' },
    { src: "/homestudio/youstudio/imagens/img-mini-mercado.png", alt: 'Imagem 17' },
]

export const expandedYouHomeImages = [
    { src: "/homestudio/youstudio/imagens/expanded/1.png", alt: 'fachada' },
    { src: "/homestudio/youstudio/imagens/expanded/2.png", alt: 'fachada2' },
    { src: "/homestudio/youstudio/imagens/expanded/3.png", alt: 'fachada3' },
    { src: "/homestudio/youstudio/imagens/expanded/4.png", alt: 'porte-cochère' },
    { src: "/homestudio/youstudio/imagens/expanded/5.png", alt: 'lobby social' },
    { src: "/homestudio/youstudio/imagens/expanded/6.png", alt: 'SAUNA/REPOUSO E PISCINA AQUECIDA' },
    { src: "/homestudio/youstudio/imagens/expanded/7.png", alt: 'sauna' },
    { src: "/homestudio/youstudio/imagens/expanded/8.png", alt: 'fit studio' },
    { src: "/homestudio/youstudio/imagens/expanded/9.png", alt: 'espaço gourmet' },
    { src: "/homestudio/youstudio/imagens/expanded/10.png", alt: 'lavanderia' },
    { src: "/homestudio/youstudio/imagens/expanded/11.png", alt: 'coworking' },
    { src: "/homestudio/youstudio/imagens/expanded/12.png", alt: 'studio' },
    { src: "/homestudio/youstudio/imagens/expanded/13.png", alt: 'studio' },
    { src: "/homestudio/youstudio/imagens/expanded/14.png", alt: 'delivery' },
    { src: "/homestudio/youstudio/imagens/expanded/15.png", alt: 'sala de entregas' },
    { src: "/homestudio/youstudio/imagens/expanded/16.png", alt: 'pet care' },
    { src: "/homestudio/youstudio/imagens/expanded/17.png", alt: 'mini mercado' },
];
